### ISSUE TITLE
Ability to upload to multiple Azkaban instances

### ISSUE THREAD

**Issue by convexquad** [linkedin/linkedin-gradle-plugin-for-apache-hadoop#110]
Update the .azkabanPlugin.json file so that it supports a list of named Azkaban instances. One of them will be the "default" instance. Currently, the file looks like:

```
{
    "azkabanUrl": "https://ltx1-holdemaz01.grid.linkedin.com:8443",
    "azkabanProjName": "abain-xgboost-demo",
    "azkabanZipTask": "azkabanHadoopZip",
    "azkabanValidatorAutoFix": "true",
    "azkabanUserName": "abain"
}
```

It should look something like:

```
{
  {
    // Instance that has no name is the default one
    "azkabanUrl": "https://myDefaultAzkabanInstance.linkedin.com:8443",
    "azkabanProjName": "myAzkabanProject",
    "azkabanZipTask": "azkabanHadoopZip",
    "azkabanValidatorAutoFix": "true",
    "azkabanUserName": "abain"
  },
  {
    "azkabanName": "secondInstance"   
    "azkabanUrl": "https://secondInstance.linkedin.com:8443",
    "azkabanProjName": "myOtherProject",
    "azkabanZipTask": "azkabanHadoopZip",
    "azkabanValidatorAutoFix": "true",
    "azkabanUserName": "abain"
  },
  ...
}
```

This enhancement needs to be done in such a way that it is backwards compatible with the existing format of the .azkabanPlugin.json file, or perhaps it notices when the file is in the old format and automatically updates it.

In the azkabanUpload task you would pass -PazkabanName=secondInstance on the command line to use the second config. In the interactive mode if the user makes any edits to the values we would ask them if they want to save the changes to the same instance, or to created a new named instance and save the changes to that instance.

**Comment by pranayhasan** [comment]
@convexquad How often does users have this user-case? 
.azkabanplugin.json is project dependent, so we have one file each for a project. I believe most of our users upload to test cluster or prod. Once users are done testing, they change it to prod and they are done.
It's a good enhancement, but are we overdoing it? I think it would confuse a lot of new users to adopt to this change. Feel free to put your argument.

**Comment by convexquad** [comment]
@pranayhasan Two people have asked me about it so far. In general, LinkedIn is heading to a future where it has many different clusters, so I do think that this is a useful enhancement. However, I agree that we should be careful about overdoing it and be careful about providing features that are not actually that helpful.

If you don't like this enhancement as much, it is ok with me if we end up prioritizing it lower than other ideas we have.

**Comment by prokod** [comment]
I would say it would be very useful if we could have this feature but with a twist, while still supporting deployment to different Azkaban instances also supporting different combinations of `azkabanProjName` and `azkabanZipTask`. this will require IMO to enhance the upload task in the plugin in a similar manner that the hadoopZip taks behaves where different tasks are created base on the exisiting combination available in the json file.

**Comment by pranayhasan** [comment]
This issue has been pending since long, would close this ASAP.

**Comment by jakhani** [comment]
**First Way:**
We can also provide a way to pass any of these parameters in command to overwrite .azkabanPlugin.json value.
For e.g.  ligradle azkabanExecuteFlow --no-daemon --azkabanUrl=https://anyurl.linkedin.com:8443
It will not add any complexity and it can be completed in less time.

**Second Way:**
If we want to provide support for multiple instances then we can define instances as prod, test and dev. We can allow single instance per type. Every multiproduct user can configure their dev, test and prod cluster URLs. This will require more time than above solution.

**Comment by pranayhasan** [comment]
@jakhani The first way you mentioned enables users to override the default values in **.azkabanPlugin.json**. Both ways look good, but the second way is a bit involved. Also, these two are independent of each other, so you can go ahead and close this issue with the first way.
