### ISSUE TITLE
I can't find any examples

### ISSUE THREAD

**Issue by doctorpangloss** [linkedin/linkedin-gradle-plugin-for-apache-hadoop#117]
I'd love to use this plugin. I assume it can help me bundle a Hadoop application and actually run it. I can't quite figure out how to do that. How would I use this with the Hadoop WordCount2 example?

**Comment by pranayhasan** [comment]
Thanks for your interest in using the plugin. You should be either using Azkaban/Oozie for you to be able to run Hadoop examples with JavaProcessJob as your Job type. Please go through the documentation for details.

**Comment by convexquad** [comment]
@doctorpangloss Thanks for writing us! The Hadoop Plugin is super useful in the case that you are using Azkaban as the scheduler / executor for your Hadoop jobs.

In that case, start with the documentation for the Plugin at https://github.com/linkedin/linkedin-gradle-plugin-for-apache-hadoop/wiki/User-Guide and for the Hadoop DSL at https://github.com/linkedin/linkedin-gradle-plugin-for-apache-hadoop/wiki/Hadoop-DSL-Language-Reference.

If you aren't using Azkaban, the Hadoop Plugin does have some useful features, but is probably not going to save you lots of time versus just doing things however you are doing them now.

**Comment by convexquad** [comment]
Closed by https://github.com/linkedin/linkedin-gradle-plugin-for-apache-hadoop/pull/153
