### ISSUE TITLE
runSparkJob will fail if running python Spark job.

### ISSUE THREAD

**Issue by coderant** [linkedin/linkedin-gradle-plugin-for-apache-hadoop#80]
1. In the source code, it checks for the same logic as the old required fields.
[source code](https://github.com/linkedin/linkedin-gradle-plugin-for-apache-hadoop/blob/606e643a7e309d0c181b7d9b3ab6d2e3168fd85e/hadoop-plugin/src/main/groovy/com/linkedin/gradle/spark/SparkPlugin.groovy#L157-L163)
If Hadoop dsl checker will check this, is it necessary to have SparkPlugin check it again?

2. Also the build spark command method will not produce the right command. 
Because it's doing [this](https://github.com/linkedin/linkedin-gradle-plugin-for-apache-hadoop/blob/f083981f84464f5a1e81f647e681cdd0fded38b8/hadoop-plugin/src/main/groovy/com/linkedin/gradle/spark/SparkSubmitHelper.groovy#L68-L70)
The `--class` option should be neglected if `appClass` is null.

**Comment by convexquad** [comment]
Ah - the Hadoop DSL static checker will only be applied if you are compiling to Azkaban. If you are running from the gateway, it won't apply the static checker (and should not), it should merely validate whatever fields are necessary to launch the job on the gateway. We definitely need to make the same set of patches to the task to accomodate PySpark jobs

**Comment by coderant** [comment]
Ah I see. I'll make the corresponding changes and send a PR.
I'll ping you if I can't make it or run into any problems.
Thanks Alex!

**Comment by convexquad** [comment]
This was closed by #83
