### ISSUE TITLE
Enable azkabanUpload task to validate session before uploading

### ISSUE THREAD

**Issue by pranayhasan** [linkedin/linkedin-gradle-plugin-for-apache-hadoop#90]
For an invalid session, the azkabanUpload task performs uploading the zip twice where the first POST request fails and the further request succeeds. Thus it takes twice the time necessary for uploading the zip, if the session is invalid. A quick fix is to check each time if the session is valid and then proceed with upload. @convexquad @nntnag17 @akshayrai Please let me know if there is a better way, if any.

**Comment by convexquad** [comment]
@pranayhasan How would you check if the session is valid? Is there something you can reliably call in Azkaban to check?

**Comment by pranayhasan** [comment]
It can be made by calling azkaban API like [fetchprojectflows](http://azkaban.github.io/azkaban/docs/latest/#api-fetch-flows-of-a-project) which just needs project name as a parameter.

**Comment by convexquad** [comment]
I think that API endpoint sounds good. In addition to verifying if the user has logged in, it might be nice to use this to verify that the project they specified exists. +1 to this enhancement

**Comment by convexquad** [comment]
@pranayhasan Ok this happened to me today when I was uploading, and I needed to enter my password. I agree that this would be a good enhancement.

**Comment by pranayhasan** [comment]
#98
